# Generated by Django 5.2.3 on 2025-07-14 09:12

import crm.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('type_of_company', models.CharField(max_length=100)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='EST', max_length=10)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GSTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('lead_no', models.CharField(default=crm.models.generate_lead_no, max_length=10, unique=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('requirement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(max_length=100, unique=True)),
                ('quote_date', models.DateField(default=django.utils.timezone.now)),
                ('lead_no', models.CharField(blank=True, max_length=50, null=True)),
                ('validity_days', models.PositiveIntegerField()),
                ('gst_no', models.CharField(blank=True, max_length=30, null=True)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_received_date', models.DateField(blank=True, null=True)),
                ('po_attachment', models.FileField(blank=True, null=True, upload_to='po_attachments/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('lost_reason', models.TextField(blank=True, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='EstimationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.estimation')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('invoice_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.estimation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utr_number', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales', 'Sales Executive')], default='sales', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.estimation')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
