# Generated by Django 5.2.3 on 2025-09-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial Paid', 'Partial Paid'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
