# Generated by Django 5.2.3 on 2025-07-14 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
