# Generated by Django 5.2.3 on 2025-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_lead_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
