# Generated by Django 5.2.3 on 2025-07-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
