# Generated by Django 5.2.3 on 2025-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lead_address_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='follow_up_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
