# Generated by Django 5.2.3 on 2025-07-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_estimation_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='lead_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.lead'),
        ),
    ]
