# Generated by Django 5.2.3 on 2025-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_estimation_lead_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='computed_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
