# Generated by Django 5.2.3 on 2025-07-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_termsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
            ],
        ),
    ]
