# Generated by Django 5.2.3 on 2025-07-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_defaultterms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultterms',
            old_name='terms',
            new_name='content',
        ),
    ]
