# Generated by Django 5.2.3 on 2025-07-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_rename_terms_defaultterms_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
