# Generated by Django 5.2.3 on 2025-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_termsandconditions_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial Paid', 'Partial Paid'), ('Pending', 'Pending')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
