# Generated by Django 5.2.3 on 2025-07-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_paymentlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
