# Generated by Django 5.2.3 on 2025-07-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_paymentlog_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
